// Loading
export const START_REQUEST = "START_REQUEST"
export const FINISH_REQUEST = "FINISH_REQUEST"

// Empreendimentos
export const EMPREENDIMENTOS_LIST_REQUEST = "@empreendimentos/LIST_REQUEST"
export const EMPREENDIMENTOS_LIST_SUCCESS = "@empreendimentos/LIST_SUCCESS"
export const EMPREENDIMENTOS_PREPARAR_EDITAR_REQUEST = "@empreendimentos/PREPARAR_EDITAR_REQUEST"
export const EMPREENDIMENTOS_PREPARAR_EDITAR_SUCCESS = "@empreendimentos/PREPARAR_EDITAR_SUCCESS"
export const EMPREENDIMENTOS_PREPARAR_NOVO_REQUEST = "@empreendimentos/PREPARAR_NOVO_REQUEST"
export const EMPREENDIMENTOS_PREPARAR_NOVO_SUCCESS = "@empreendimentos/PREPARAR_NOVO_SUCCESS"
export const EMPREENDIMENTOS_SALVAR_REQUEST = "@empreendimentos/SALVAR_REQUEST"
export const EMPREENDIMENTOS_SALVAR_SUCCESS = "@empreendimentos/SALVAR_SUCCESS"
export const EMPREENDIMENTOS_DELETAR_REQUEST = "@empreendimentos/DELETAR_REQUEST"
export const EMPREENDIMENTOS_DELETAR_SUCCESS = "@empreendimentos/DELETAR_SUCCESS"
export const EMPREENDIMENTOS_ERROR = "@empreendimentos/ERROR"
